# Generated by Django 4.0.1 on 2022-01-19 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskForParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_for_parse', models.CharField(max_length=255, verbose_name='Аккаунт для парсинга')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает'), ('in_progress', 'В процессе'), ('done', 'Выполнен')], default='waiting', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_for_parse', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача на парсинг',
                'verbose_name_plural': 'Задачи на парсинг',
            },
        ),
    ]
