# Generated by Django 4.0.1 on 2022-01-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0003_rename_username_for_parse_taskforparse_user_to_scrape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='data',
            name='business_contact_method',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Способ связи'),
        ),
        migrations.AlterField(
            model_name='data',
            name='contact_phone_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='data',
            name='follower_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во подписчиков'),
        ),
        migrations.AlterField(
            model_name='data',
            name='following_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во подписок'),
        ),
        migrations.AlterField(
            model_name='data',
            name='following_tag_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во подписок на теги'),
        ),
        migrations.AlterField(
            model_name='data',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='data',
            name='instagram_location_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='id геолокации'),
        ),
        migrations.AlterField(
            model_name='data',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Приватный ли аккаунт'),
        ),
        migrations.AlterField(
            model_name='data',
            name='media_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во публикаций'),
        ),
        migrations.AlterField(
            model_name='data',
            name='public_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='data',
            name='usertags_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во тегов пользователя'),
        ),
        migrations.AlterField(
            model_name='data',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Whatsapp'),
        ),
    ]
