# Generated by Django 4.0.1 on 2022-01-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0004_alter_data_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskforparse',
            name='file',
            field=models.FileField(blank=True, upload_to='file/%Y/%m/%d/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='instagram_location_id',
            field=models.PositiveIntegerField(default=0, verbose_name='id геолокации'),
        ),
    ]
