# Generated by Django 4.0.1 on 2022-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0005_taskforparse_file_alter_data_instagram_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='instagram_location_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='id геолокации'),
        ),
    ]
