# Generated by Django 4.0.1 on 2022-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0006_alter_data_instagram_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskforparse',
            name='status',
            field=models.CharField(choices=[('waiting', 'задача на проверке'), ('in_progress', 'задача выполняется'), ('done', 'задача выполнена'), ('error', 'ошибка при выполнении')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
    ]
