# Generated by Django 4.0.1 on 2022-01-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0008_instagramaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramaccount',
            options={'verbose_name': 'Аккаунт instagram', 'verbose_name_plural': 'Аккаунты instagram'},
        ),
    ]
