# Generated by Django 4.0.1 on 2022-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0009_alter_instagramaccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Отработал ли аккаунт'),
        ),
    ]
