# Generated by Django 4.0.1 on 2022-02-06 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0011_alter_taskforparse_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='used_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последней работы аккаунта'),
        ),
    ]
