# Generated by Django 4.0.1 on 2022-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0013_taskforparse_count_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskforparse',
            name='parse_followers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Спаршено подписчиков'),
        ),
    ]
