# Generated by Django 4.0.1 on 2022-02-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0014_taskforparse_parse_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskforparse',
            name='next_max_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='next_max_id'),
        ),
    ]
