# Generated by Django 4.0.1 on 2022-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0015_taskforparse_next_max_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskforparse',
            name='is_parse_followers',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Сбор подписчиков'),
        ),
        migrations.AddField(
            model_name='taskforparse',
            name='is_parse_following',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Сбор подписок'),
        ),
    ]
