# Generated by Django 4.0.1 on 2022-02-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0016_taskforparse_is_parse_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskforparse',
            name='is_parse_following',
        ),
        migrations.AlterField(
            model_name='taskforparse',
            name='is_parse_followers',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Сбор подписчиков'),
        ),
    ]
