# Generated by Django 4.0.1 on 2022-02-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0017_remove_taskforparse_is_parse_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskforparse',
            name='is_parse_followers',
        ),
        migrations.AddField(
            model_name='taskforparse',
            name='type_of_parse',
            field=models.CharField(choices=[('followers', 'Cбор подписчиков'), ('following', 'Сбор подписок')], default='followers', max_length=20, verbose_name='Тип сбора данных'),
        ),
    ]
