# Generated by Django 4.0.1 on 2022-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaparser', '0018_remove_taskforparse_is_parse_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskforparse',
            name='count_followers',
        ),
        migrations.RemoveField(
            model_name='taskforparse',
            name='parse_followers',
        ),
        migrations.AddField(
            model_name='taskforparse',
            name='count_parse_data',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Спаршено данных'),
        ),
    ]
